/// Flutter icons YcApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  YcApp
///      fonts:
///       - asset: fonts/YcApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class YcAppIcons {
  YcAppIcons._();

  static const _kFontFam = 'YcApp';
  static const _kFontPkg = null;

  static const IconData jingle_jam = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
